### ISSUE TITLE
Add new classifications to compound report card page

### ISSUE THREAD

**Issue by mark-davies** [chembl/user_interface#3]
Add IRAC, FRAC and HRAC classifications to compound report card pages

**Comment by mark-davies** [comment]
Added IRAC, FRAC and HRAC classifications, examples:

IRAC: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL46917
FRAC: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL625
HRAC: http://wwwdev.ebi.ac.uk/chembl/compound/inspect/CHEMBL34474

Could not find suitable external links for identifiers

**Comment by agaulton** [comment]
Slightly more specific links for the IRAC/FRAC/HRAC (there is no linking on individual compound though as far as I'm aware):
http://www.irac-online.org/documents/moa-brochure/?ext=pdf
http://www.frac.info/publication/anhang/2014%20FRAC%20Code%20List.pdf
http://www.hracglobal.com/Education/ClassificationofHerbicideSiteofAction.aspx

Also for the bottom level code in each hierarchy could we display the 'active_ingredient' as it's description rather than the 'irac_code' etc? i.e., for CHEMBL46917 above, it would read 'A11A7 - CARBARYL'

**Comment by mark-davies** [comment]
Updated with new links and active_ingredient name

**Comment by agaulton** [comment]
This is great now, thanks, can close
