### ISSUE TITLE
Metabolism view

### ISSUE THREAD

**Issue by agaulton** [chembl/user_interface#56]
A couple of minor things:

e.g., https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/4941
If you click on the 'NAT2' link between acetyl hydrazine and diacetyl hydrazine...

1) There are a large number of references but many of them are duplicates. I am not quite sure how we get so many. There should be 4 distinct references for this step, but there are two rows for this same reaction (met_id = 1148 and met_id = 1149), so I could see how we could get 8, but not 48... Is it possible to check the query and/or make these non-redundant on your side? I can change the function if required to take the substrate and metabolite IDs (rather than met_id) and return a non-redundant list.

2) There should be two enzymes for this step (NAT2 and CYP2E1), but we are only showing one (I understand only one may be possible to display on the edge, but is there a straightforward way to show all of the enzymes in the pop-up box?). Same could be true for organism...

**Comment by agaulton** [comment]
3) When the enzyme_tid is 22226 (CHEMBL612545) e.g., on the isoniazid to pyruvic acid hydrazine link, we shouldn't show this in the 'Enzyme' field on the pop up box (this tid is just a placeholder that isn't really an enzyme).

**Comment by nclopezo** [comment]
I removed the duplicate references, and not it "curves" the arrow when there are 2 or more edges with the same source and target:

https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/4941

The query still needs to be fixed, It still fails with "result of string concatenation is too long" for the cases described in https://github.com/chembl/user_interface/issues/57.

The case of CHEMBL612545, how can I distinguish a placeholder from a real enzyme?

**Comment by nclopezo** [comment]
Would it be when the preferred name is null?

**Comment by agaulton** [comment]
You could either use target_dictionary target_type = 'UNCHECKED' or pref_name = 'Unchecked' or just tid = 22226. This is the only case where we wouldn't want to show an enzyme

**Comment by agaulton** [comment]
I made a function to deal with the duplicate /too long references - see email

**Comment by nclopezo** [comment]
I added the function and made it remove the "Enzyme" field:

https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/4941

With the new function now https://github.com/chembl/user_interface/issues/57 seems resolved.

 https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/27072
https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/674915

Not all the images are shown because they are using www, instead of wwdev. 
When chembl22 is in production tho images should work.

For example:
chembl21: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL3638287?engine=indigo
chembl22: https://wwwdev.ebi.ac.uk/chembl/api/data/image/CHEMBL3638287?engine=indigo

**Comment by nclopezo** [comment]
I just deployed the change of colour of the edges:

https://wwwdev.ebi.ac.uk/chembl/compound/metabolism/4941

**Comment by agaulton** [comment]
great thanks
